language: ruby
rvm:
 - 2.3.1
script: bundle exec rspec spec
services:
  - mysql
  - redis-server
  - elasticsearch
before_script:
  - sleep 10
  - mysql -e 'create database boxes_test;'
  - bundle exec rails db:setup